// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://swtihvkvbmljpwslcoub.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN3dGlodmt2Ym1sanB3c2xjb3ViIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjEwNTUsImV4cCI6MjA2Mzc5NzA1NX0.Z4nuTSMLXV4YN-UBOnJXS6pkrh7SeRzMmn_LLJXlnSA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);